SET PYTHON_EXE=c:\ProgramData\robocorp\ht\cd7858c_5a1fac3_9fcd2534\python.exe
SET PYTHONDONTWRITEBYTECODE=x
SET PYTHONPYCACHEPREFIX=C:\Users\cosminpopa\AppData\Local\robocorp\temp\44296f6d9d0a20e2
SET TEMP=C:\Users\cosminpopa\AppData\Local\robocorp\temp\44296f6d9d0a20e2
SET TMP=C:\Users\cosminpopa\AppData\Local\robocorp\temp\44296f6d9d0a20e2
SET CONDA_DEFAULT_ENV=rcc
SET CONDA_PREFIX=c:\ProgramData\robocorp\ht\cd7858c_5a1fac3_9fcd2534
SET CONDA_PROMPT_MODIFIER=(rcc)
SET CONDA_SHLVL=1
SET PYTHONHOME=
SET PYTHONSTARTUP=
SET PYTHONEXECUTABLE=
SET PYTHONNOUSERSITE=1
SET ROBOCORP_HOME=C:\Users\cosminpopa\AppData\Local\robocorp
SET RCC_ENVIRONMENT_HASH=2f4a48b6e779bb2e
SET RCC_INSTALLATION_ID=ddf0dbe5-c5f4-a533-f5e6-ef5d07b04ec9
SET RCC_HOLOTREE_SPACE_ROOT=c:\ProgramData\robocorp\ht\cd7858c_5a1fac3_9fcd2534
SET RCC_TRACKING_ALLOWED=true
SET RCC_EXE=C:\Users\cosminpopa\Downloads\rcc.exe
SET RCC_VERSION=v17.12.0
SET PATH=c:\ProgramData\robocorp\ht\cd7858c_5a1fac3_9fcd2534;c:\ProgramData\robocorp\ht\cd7858c_5a1fac3_9fcd2534\Library\mingw-w64\bin;c:\ProgramData\robocorp\ht\cd7858c_5a1fac3_9fcd2534\Library\usr\bin;c:\ProgramData\robocorp\ht\cd7858c_5a1fac3_9fcd2534\Library\bin;c:\ProgramData\robocorp\ht\cd7858c_5a1fac3_9fcd2534\Scripts;c:\ProgramData\robocorp\ht\cd7858c_5a1fac3_9fcd2534\bin;C:\Program Files\Parallels\Parallels Tools\Applications;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Yarn\bin;C:\Users\cosminpopa\Downloads\%NVM_HOME%;C:\Users\cosminpopa\Downloads\%NVM_SYMLINK%;C:\Program Files\Git\cmd;C:\Program Files\Java\jdk1.8.0_211\bin;C:\Users\cosminpopa\AppData\Local\Microsoft\WindowsApps;C:\Users\cosminpopa\AppData\Local\Yarn\bin;C:\Users\cosminpopa\AppData\Roaming\npm;C:\ProgramData\nvm;C:\Program Files (x86)\nodejs;C:\Users\cosminpopa\AppData\Local\Programs\Microsoft VS Code\bin
SET CONDA_PREFIX=C:\ProgramData\robocorp\ht\cd7858c_5a1fac3_9fcd2534
SET CONDA_PREFIX_1=c:\ProgramData\robocorp\ht\cd7858c_5a1fac3_9fcd2534
SET CONDA_PROMPT_MODIFIER=(C:\ProgramData\robocorp\ht\cd7858c_5a1fac3_9fcd2534)
SET CONDA_SHLVL=2
SET MAMBA_ROOT_PREFIX=C:\Users\cosminpopa\AppData\Local\robocorp
SET PATH=C:\ProgramData\robocorp\ht\cd7858c_5a1fac3_9fcd2534;C:\ProgramData\robocorp\ht\cd7858c_5a1fac3_9fcd2534\Library\mingw-w64\bin;C:\ProgramData\robocorp\ht\cd7858c_5a1fac3_9fcd2534\Library\usr\bin;C:\ProgramData\robocorp\ht\cd7858c_5a1fac3_9fcd2534\Library\bin;C:\ProgramData\robocorp\ht\cd7858c_5a1fac3_9fcd2534\Scripts;C:\ProgramData\robocorp\ht\cd7858c_5a1fac3_9fcd2534\bin;C:\Program Files\Parallels\Parallels Tools\Applications;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Yarn\bin;C:\Users\cosminpopa\Downloads\C:\ProgramData\nvm;C:\Users\cosminpopa\Downloads\C:\Program Files (x86)\nodejs;C:\Program Files\Git\cmd;C:\Program Files\Java\jdk1.8.0_211\bin;C:\Users\cosminpopa\AppData\Local\Microsoft\WindowsApps;C:\Users\cosminpopa\AppData\Local\Yarn\bin;C:\Users\cosminpopa\AppData\Roaming\npm;C:\ProgramData\nvm;C:\Program Files (x86)\nodejs;C:\Users\cosminpopa\AppData\Local\Programs\Microsoft VS Code\bin
SET PROMPT=$P$G
SET CONDA_DEFAULT_ENV=C:\ProgramData\robocorp\ht\cd7858c_5a1fac3_9fcd2534

SET RC_JAVA_ACCESS_BRIDGE_DLL=C:\\Program Files\\Java\\jdk1.8.0_211\\jre\\bin\\WindowsAccessBridge-64.dll