name: java-access-bridge-wrapper

on:
  push:
     paths:
      - src/**
      - .github/workflows/**

jobs:
  lint:
    # Not using the latest ubuntu until this issue is fixed in setup-python:
    # https://github.com/actions/setup-python/issues/401
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.12
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install requirements
      run: pip install -Ur requirements.txt
    - name: Set up cache
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ hashFiles('poetry.lock') }}
    - name: Install dependencies
      run: invoke update
    - name: Run lint
      run: invoke lint